### ISSUE TITLE
Latest-N parameter broken in Langviews

### ISSUE THREAD

**Issue by Krinkle** [MusikAnimal/pageviews#114]
At [https://tools.wmflabs.org/langviews/](https://tools.wmflabs.org/langviews/?project=en.wikipedia.org&platform=all-access&agent=user&range=latest-60&sort=views&direction=1&page=Star_Wars)

> [स्तार वार्स](https://new.wikipedia.org/wiki/स्तार_वार्स) Error querying Pageviews API - Not found.
> https://new.wikipedia.org/wiki/स्तार_वार्स

**Comment by MusikAnimal** [comment]
I think this might actually be a bug with the `latest-N` option. On Pageviews with the latest-60 range we see that data for this article is shown. Latest-60 on Langviews is actually showing the past month's data, and during that time this article did not exist on that wiki (presumably it was imported at some point from another wiki).

**Comment by MusikAnimal** [comment]
Ah, actually, there was a max of 30 days for this tool, so it went with 30 days from the given start date (60 days ago). During that time the article did not exist, which is why you got the error.

I have changed the max range to 90 days. Unlike the main Pageviews tool, Langviews can be a very heavy operation on the API so we need to limit to something. I think 90 will be OK.
