### ISSUE TITLE
Use log scale in graphs with big variance

### ISSUE THREAD

**Issue by nemobis** [MusikAnimal/pageviews#125]
In a graph like https://tools.wmflabs.org/pageviews/?project=it.wikipedia.org&platform=all-access&agent=user&start=2016-05-01&end=2016-05-30&pages=Salvatore_Aranzulla where there is a lot of variance (three distinct periods where daily visits were respectively in the range 0-20, 100k-150k and 100-1500), it would be useful to automatically use log scale.

The [Theil index](https://en.wikipedia.org/wiki/Theil_index) is especially easy to calculate, if you don't have a built-in method to identify that sort of situation.

**Comment by MusikAnimal** [comment]
It's on the radar! See #35

Originally I was planning to use the new version of the Chart.js library, which has this functionality. However there are several blockers in #42 that got in the way. There is a "patch" I can apply to the current version we use, but it's tricky because we're already working off of a fork of the original version.

That being said I think the extra is still worthwhile, as development to address the outstanding issues with 2.0 are slow to happen, it seems.

**Comment by MusikAnimal** [comment]
Thanks for pointing the Theil index, even with Chart.js 2.0 we would not be able to automatically tell if a log scale is needed.

Closing this issue to keep them consolidated, and have upped #35 to be high-priority
