### ISSUE TITLE
Cannot get pageviews to work

### ISSUE THREAD

**Issue by PaineEllsworth** [MusikAnimal/pageviews#130]
I've been trying to get pageviews to work since yesterday - see https://en.wikipedia.org/wiki/Wikipedia:Help_desk#wmflabs_Pageviews_Analysis_broken.3F

The page opens and the circle in the center just continues to revolve.  As a test I tried:  https://tools.wmflabs.org/pageviews/?project=en.wikipedia.org&platform=all-access&agent=user&start=2015-07-01&end=2016-04-30&pages=Sangha%7CSangha_%28Buddhism%29%7CSangha_Department_%28Republic_of_the_Congo%29%7CSangha_Department_%28Burkina_Faso%29%7CSangha,_Mali%7CJain_community%7CSangha_%28disambiguation%29

and received the same result - a continuously revolving circle.

**Comment by MusikAnimal** [comment]
@PaineEllsworth This was definitely broken at some point, but should be working for you now. A few days ago we [released](https://github.com/MusikAnimal/pageviews/releases/tag/2016.06.21T23.17) a major update to the tool, that included a logarithmic scale option. For pages that received zero page views at any point, the chart would break because `log(0)` is not defined. This was fixed with the [2016-06-23](https://github.com/MusikAnimal/pageviews/releases/tag/2016.06.23T15.55) release, so you shouldn't have this issue any more.

Could you share which browser and operating system you are using? For example, Chrome 51 on Windows 7.

Please also try using the tool in a different browser, or in incognito mode. There is a possibility there's some inadvertent caching going on.

**Comment by PaineEllsworth** [comment]
Sorry no - that is, if you click on the long link above, which compares pages about Sangha, all you get is the revolving circle.  Is there now something perhaps wrong with the link itself?  Anyway, I browse and edit with IE11 on Windows 10.  and I sometimes use uSoft-Edge, although I feel it's little better than Chrome or Firefox.  I shall reboot and see if that helps.

**Comment by MusikAnimal** [comment]
@PaineEllsworth I tried it out with IE11 on Windows 7 and it worked. I don't think Windows 10 has anything to do with it.

Please try using a different browser. If it works, that means IE is somehow caching it. Try forcing a full reload with Ctrl + F5

**Comment by PaineEllsworth** [comment]
Ctrl + F5 didn't work.  You're correct in that I have no problem loading pageviews in Chrome, Firefox or Edge.  I sent a report to uSoft, and I wish myself good luck with that.  Thank you for your help in this, MusikAnimal!

**Comment by MusikAnimal** [comment]
@PaineEllsworth No problem! :) I still think it's a caching issue. Could you hit Ctrl+Shift+P and try it in private browsing? Private browsing will ignore caching. If it works there, than you should be able to [manually clear your cache](http://refreshyourcache.com/en/internet-explorer-11/) to fix it permanently.

**Comment by PaineEllsworth** [comment]
You appear to be correct about the caching, but there doesn't seem to be anything I can do about it.  I've tried everything you've suggested, and when nothing worked, uSoft gave some lame excuse about the last resort being that my ISP is caching the non-working page.  If that were truly so, then wouldn't the other browsers also have the same problem as IE?  This is not the first time I've encountered this, only the first time with the pageviews page.  It worked just fine two weeks ago, but now? nada.  Doesn't seem to anything that will fix it.  Maybe I can sneak in and enlarge the cache?  But if I've force-cleared it, then there must be plenty of room, so that can't be the problem.  I'll fiddle with it some more.  Thanks again for all your help!
