### ISSUE TITLE
CSS/JavaScript blocked by AdBlockPlus

### ISSUE THREAD

**Issue by nemobis** [MusikAnimal/pageviews#15]
The default rules of AdBlockPlus 2.7.1 block all the CSS and JavaScript resources of the tool from loading. ABP has tens of millions of users and is even included by default in some OS, would be nice to respect its wishes. :)

**Comment by MusikAnimal** [comment]
See [T126947](https://phabricator.wikimedia.org/T126947). It appears it's blocking the pageviews API itself, so unfortunately beyond my control :/

**Comment by nemobis** [comment]
MusikAnimal, 15/02/2016 04:39:
> It appears it's blocking the pageviews API itself

That's not what I'm talking about though. I mean the block of 
application.js and application.css, perhaps by EasyPrivacy.

**Comment by MusikAnimal** [comment]
Yes that's apparently a consequence, perhaps since the assets are nested under a `/pageviews/*` which happens to be the same routing as the tool itself. E.g. if I remove the code that queries the API, application.js, application.css and all the other assets load as expected. This tells me the API is the sole culprit.

**Comment by MusikAnimal** [comment]
See https://phabricator.wikimedia.org/T128974

**Comment by MusikAnimal** [comment]
We've basically done all we can do here, and I think many people's ad blockers have auto-updated and hence the tool works now. More at https://phabricator.wikimedia.org/T128974

Closing
