### ISSUE TITLE
Add a license statement for the graphs

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MusikAnimal/pageviews#191]
We re thinking of using from https://tools.wmflabs.org/pageviews/?project=en.wikipedia.org&platform=all-access&agent=user&start=2016-04-01&end=2016-05-01&pages=Hypercycle_(chemistry) and https://tools.wmflabs.org/pageviews/?project=en.wikipedia.org&platform=all-access&agent=user&start=2016-04-01&end=2016-05-02&pages=Hypercycle_(chemistry) as figures in a scholarly article, which is to be published under a [CC BY license](https://creativecommons.org/licenses/by/4.0/).

I could not find any statement in the repo or on the tool's website as to what the licensing of the generatedd graphs might be. Can you clarify that? Can we publish the above charts under CC BY? WIth what attribution?

Thanks.

**Comment by MusikAnimal** [comment]
Hi! The code itself is published under the MIT license: https://github.com/MusikAnimal/pageviews/blob/master/LICENSE

The rendered charts are using the [Chart.js](https://github.com/chartjs/Chart.js) library, also released under the MIT license.

The underlying data is from the Wikimedia REST API, released under CC-BY-SA 3.0 and GDFL license: https://wikimedia.org/api/rest_v1/

So, if you're just using the data, defer to the API's license. Obviously you're not using any code, so no worries there. If you're using screenshots, a linkback to https://tools.wmflabs.org/pageviews would be appreciated and plenty sufficient :)

I'll add something to the README, because you're right that this should be documented.

Thanks for asking!

**Comment by MusikAnimal** [comment]
So I got that wrong, the pageviews data from the API is released under the [CC0 1.0 license](https://creativecommons.org/publicdomain/zero/1.0/), aka the public domain. At https://wikimedia.org/api/rest_v1/ you have to expand each endpoint to see that.

Anyway, you are perfectly safe to use the data and/or charts in your article. I consent that you don't even need to link back to Pageviews Analysis, or provide attribution, unless you're using a screenshot of the entire application. The charts alone are free to use without attribution. Thanks again :)
