### ISSUE TITLE
Usability: Shorten display dates

### ISSUE THREAD

**Issue by rhoio** [MusikAnimal/pageviews#53]
Dates in the graph are currently displayed as 2016-03-20T00:00:00+01:00, making it very hard to read.
Shortening it to just display the date like 2016-03-20 in the legend and the hover-tooltip would be much nicer.

**Comment by MusikAnimal** [comment]
@rhoio What browser/operating system are you using? You should not be seeing timestamps like that

**Comment by rhoio** [comment]
I'm using chrome Version 49.0.2623.87 (64-bit) on Macos X 10.10.5, page accessed following the link https://tools.wmflabs.org/pageviews/#project=de.wikipedia.org&platform=all-access&agent=user&start=2016-03-15&end=2016-04-03&pages=Test
on the german wikipedia:
![wikitest-chrome](https://cloud.githubusercontent.com/assets/5052868/14263324/51343aa8-faba-11e5-88db-3499a5a261dc.png)

Same link on safari looks okay (short dates), while Firefox hangs and doesn't display the chart at all:

> TypeError: d.responseJSON is undefined
> ...ength||($(".chart-container").html(""),$(".chart-container").removeClass("loadin...
> in application.js

**Comment by rhoio** [comment]
correction regarding firefox (45.0.1): it seems to collide with the standard settings of the plugin ublock origin.
When I switch the plugin off, it displays the chart but with the long timestamps, same as chrome.

**Comment by MusikAnimal** [comment]
@rhoio Alright I know what happened, simple bug fix. Please try it out now and confirm you are seeing a sensible format.

This happened because your browser's language setting was something we didn't explicitly support. The fix was just to give it a fallback, but I'm curious what you have set. Since you apparently know how to work the web inspector, would you mind opening up your JS console and letting me know what `navigator.language` evaluates to?

**Comment by rhoio** [comment]
Works on firefox and chrome now, thanks :-) navigator.language ist set to "de" in both browsers.

**Comment by MusikAnimal** [comment]
No problem, thank you for the report! It probably has been like that for a while. I don't know why your computer is set to just `de`, typically we see a country code associated with the language. Closing
