### ISSUE TITLE
Make it possible to show the site-level data as well/instead

### ISSUE THREAD

**Issue by jdforrester** [MusikAnimal/pageviews#68]
A query like [this one](https://wikimedia.org/api/rest_v1/metrics/pageviews/aggregate/en.wikipedia/all-access/all-agents/daily/2016040100/2016041400) will get site-level (rather than page-level) data, which might be interesting to show too?

**Comment by MusikAnimal** [comment]
Definitely! This has not been requested yet, but I'd like to take advantage of all the neat stuff we can do with the API. Here we'd need some sort of UI change, since currently everything is geared around inputting individual articles. Any thoughts on this are welcomed.

I was thinking maybe a whole new page that would resemble Pageviews, except instead of inputting articles you input projects. We could call it "ProjectViews" :)

**Comment by MusikAnimal** [comment]
@jdforrester Siteviews is live! http://tools.wmflabs.org/siteviews

Probably has numerous bugs, but it works. The big thing is the load time. It pulls in the name of every single wiki, which is already saved on disk, but the Select2 library takes FOREVER to load it. I need to implement some sort of hack to make it place nice.

Another to-do is to add an option to change the granularity, since this API endpoint supports it. E.g. we could compare projects on an hourly basis, which might be interesting to see.

Any other feedback welcomed! Going to go ahead and close this, and open new issues for additional features/bugs.

Cheers
