### ISSUE TITLE
Please use iso8601 date format

### ISSUE THREAD

**Issue by Boshomi** [MusikAnimal/pageviews#75]
Yes, I know there a a lot of different ways to write a date as number: http://imgs.xkcd.com/comics/iso_8601.png

for europeans the US-format is very hard to read, and sometimes misleading  (please note that the UK format is dd/mm/yyyy it is hard for none english speaking people to detect if it is UK or US format). 

So please use the international ISO 8601 format instead.

**Comment by MusikAnimal** [comment]
@Boshomi The date format goes off of your computer settings. Could you confirm that you see your language code when running [this test](https://jsfiddle.net/bhytx332/)? If it is set to US English, you should see `en-US`. If it is not, please tell me which code you see and I can update the format accordingly. The fallback for unknown formats should be ISO 8601.

**Comment by MusikAnimal** [comment]
I'm going to guess you are using a browser that does not support the [Navigator interface](https://developer.mozilla.org/en-US/docs/Web/API/Navigator). If this is the case, you would have seen US English date formats. I've since changed this to fallback to ISO 8601. Please confirm this is working for you.

**Comment by MusikAnimal** [comment]
This should be fixed
